AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lifescope generator lambda function.

Resources:
  
  consumer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: consumer/index.handler
      Runtime: nodejs6.10
      Events:
        consumer:
          Type: Api
          Properties:
            Path: /consumer
            Method: any