service: generator

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  generator:
    handler: index.handler
    environment:
      MONGO_ADDRESS: "mongodb://localhost:27017"
      QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/406541971079/lifescope-generator"
